spring.application.name=inventoryservice
# Puerto 8083 para que no choque con Payment(8082) ni Order(8080)
server.port=8083

# --- CONFIGURACIÓN MYSQL (Docker puerto 3307) ---
spring.datasource.url=jdbc:mysql://localhost:3307/orders?serverTimezone=GMT-5&createDatabaseIfNotExist=true
spring.datasource.username=orders
spring.datasource.password=uptc2026
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- CONFIGURACIÓN KAFKA ---
spring.kafka.bootstrap-servers=localhost:29092
# Importante: Un grupo diferente para que no compita con Payment
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer