spring.application.name=paymentservice
server.port=8084

# Base de datos H2 (Diferente motor)
spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilita la consola
spring.h2.console.enabled=true
# Asegura la ruta sin espacios
spring.h2.console.path=/h2-console
# ESTA ES LA CLAVE: Permite que se vea la interfaz gráfica
spring.h2.console.settings.web-allow-others=true

# Kafka: usa la variable de entorno si existe, si no, usa localhost
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}